### ISSUE TITLE
Questions / feature requests

### ISSUE THREAD

**Issue by aPaci95** [hgiesel/anki_grid_fields#1]
Hello, i would like to ask if it's possible to fix the fields size: for example if i fill a certain field, it will spread while the other fields will shrink. Would it be possible to add an option to have fixed size fields? It would be useful to people that like me rely on visual memory to quickly find fields to edit.
Also, if i fill certain fields too much, an horizontal navigation bar will appear. Would it be possibile to add an option to prevent this? 
For example
![image](https://user-images.githubusercontent.com/25055620/114024359-3c495800-9874-11eb-87f3-19a1cbe7433e.png)
![image](https://user-images.githubusercontent.com/25055620/114024375-4408fc80-9874-11eb-85ac-7a7a855361b5.png)

Thank you very much for this addon. It's really awesome!

**Comment by hgiesel** [comment]
First time I noticed it, I wasn't quite sure whether it was a bug or feature, but I agree with you it's more annoying than helpful.

**Comment by aPaci95** [comment]
I had the same impression, it looked like a cool feature at first but then after some usage it started to be more bothersome than useful... anyway the addon is wonderful! I waited something like this for ages! Do you think it would be possible to add an option to prevent this behaviour?
Also, i find out that when a certain field is vertically stretched, if you want to edit a field in the same row you can't just click anywhere in the field box, but you have to click in a tiny row at the top of it. 
Like this. 
![image](https://user-images.githubusercontent.com/25055620/114073053-2acb7480-98a3-11eb-9f4b-b46a99bd03a1.png)

I think that this may be due to the editable field not stretching accordingly to the field box.. maybe it could be prevented with an easy css edit but i'm not really sure...

**Comment by hgiesel** [comment]
I fixed both issues (fields resizing + clicking below the editable area). You can have another look and see whether you find any new issues :)

**Comment by aPaci95** [comment]
Thank you so much. I've got no words to explain how satistfying is to finally use something like this !
Lastly, I'm really sorry to bother you again, but i noticed that if i create more than 3-4 columns and i strecth the edit window to half my screen, it still shows an horizontal navigation bar instead of strecthing those columns. I know I may be asking too much but could it be possible to add an option to avoid showing the navigation bar and instead just stretching those columns more? 
![image](https://user-images.githubusercontent.com/25055620/114214586-c670e980-9964-11eb-9d42-4e7841be81ed.png)

For example in the image above, i only created a single row with many columns for images and i don't really care if they are stretched to microscopic size as i only need those fields to know that i put an image there...

**Comment by aPaci95** [comment]
EDIT: ok, i noticed that it still stretches the fields...
![image](https://user-images.githubusercontent.com/25055620/114215517-fa004380-9965-11eb-900a-6e4126167f1c.png)

The image doesn't show it but in the last step appeared an horizontal navigation bar..


EDIT2: ok, as i understood it only keep doing it when an image is too big or a single word is too long, while it works perfectly with phrases. I don't know if it's feasible, but maybe some sort of line break for words that are too long and a css setting that resize the image accordingly to the window size? Again, i don't want to ask too much and the addon is already wonderful, so thank you very much!

**Comment by hgiesel** [comment]
> ok, as i understood it only keep doing it when an image is too big or a single word is too long

Yep, that's why I missed it.

I just updated again, so you can see again, if it fixes all of the issues.
And thanks for being my beta-tester, so to speak :)

**Comment by aPaci95** [comment]
Now it works like a charm! There is only one last bug (it was already there before the last update): when i click in a field that is non-empty, the pointer is automatically redirected at the end of the text, so that i can only move it with the keyboard. Here is an image to explain, but if you don't understand what i'm saying i can upload a video.
![image](https://user-images.githubusercontent.com/25055620/114222055-62532300-996e-11eb-9fa5-e5718ff42805.png)

 However if you don't have this problem it may be some sort of addon incompatibility so tomorrow i'll check with only this addon enabled

**Comment by hgiesel** [comment]
Pushed another fix.

**Comment by aPaci95** [comment]
I'll test it further today but right now everything seems to work perfectly !  Thank you very much !!

**Comment by hgiesel** [comment]
You're welcome :) If you find any more issues, feel free to open another issue.
